version: '3'
services:

 visualizer:
  image: dockersamples/visualizer:stable
  ports:
   - 8000:8080
  volumes:
   - "/var/run/docker.sock:/var/run/docker.sock"
  deploy:
   mode: replicated
   replicas: 1
   labels: [APP=VISUALIZER]
   placement:
    constraints: [node.role == manager]

 portainer:
  image: portainer/portainer
  ports:
    - 8001:9000
  volumes:
   - "/var/run/docker.sock:/var/run/docker.sock"
  deploy:
   mode: replicated
   replicas: 1
   labels: [APP=PORTAINER]
   placement:
    constraints: [node.role == manager]

 prometheus:
    image: prom/prometheus
    ports:
      - 8002:9090
    volumes:
      - "./prometheus:/etc/prometheus"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=PROMETHEUS]
      placement:
        constraints: [node.role == manager]
 grafana:
  image: grafana/grafana
  ports:
    - 8003:3000
  deploy:
   mode: replicated
   replicas: 1
   labels: [APP=GRAFANA]
   placement:
    constraints: [node.role == manager]
 nodes:
   image: prom/node-exporter
   ports:
      - 9100:9100
   deploy:
      mode: global
      placement:
        constraints: [node.role == worker]
networks:
  gestbook-net:
