version: '3'
services:

 visualizer:
  image: dockersamples/visualizer:stable
  ports:
   - 8000:8080
  volumes:
   - "/var/run/docker.sock:/var/run/docker.sock"
  deploy:
   mode: replicated
   replicas: 1
   labels: [APP=VISUALIZER]
   placement:
    constraints: [node.role == manager]
  networks:
    - "admin-net"

 portainer:
  image: portainer/portainer
  ports:
    - 8001:9000
  volumes:
   - "/var/run/docker.sock:/var/run/docker.sock"
  deploy:
   mode: replicated
   replicas: 1
   labels: [APP=PORTAINER]
   placement:
    constraints: [node.role == manager]
  networks:
    - "admin-net"

 prometheus:
    image: prom/prometheus
    ports:
      - 8002:9090
    volumes:
      - "./confs/prometheus:/etc/prometheus"
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=PROMETHEUS]
      placement:
        constraints: [node.role == manager]
    networks:
      - "admin-net"

 alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - "./confs/alertmanager:/etc/alertmanager"
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=ALERTMANAGER]
      placement:
        constraints: [node.role == manager]
    networks:
      - "admin-net"

 grafana:
  image: grafana/grafana
  ports:
    - 8003:3000
  deploy:
   mode: replicated
   replicas: 1
   labels: [APP=GRAFANA]
   placement:
    constraints: [node.role == manager]
  networks:
    - "admin-net"

 nodes:
   image: prom/node-exporter
   ports:
      - 9100:9100
   deploy:
      mode: global
      placement:
        constraints: [node.role == worker]
   networks:
    - "admin-net"

networks:
  "admin-net":
    external: true
