version: '3'
services:
 spring-guestbook-stack:
  image: moconinja/spring-guestbook-test
  ports:
   - 8080:8080
  deploy:
   mode: replicated
   replicas: 3
   placement:
    constraints: [node.role == worker]
 spring-mongo-stack:
  image: mongo
  volumes:
   - /home/centos/docker/persistence/mongodb/spring-guestbook-stack:/data/db
  deploy:
   mode: replicated
   replicas: 1
   placement:
    constraints: [node.role == manager]
networks:
 gestbook-net:

