apiVersion: apps/v1
kind: Deployment
metadata:
  name: mah-webpage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: da-web
  template:
    metadata:
      labels:
        app: da-web
    spec:
      containers:
      - name: da-web
        image: moconinja/nginx-shit
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mah-web-service
spec:
  selector:
    app: da-web
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      name: http
