version: '3'
services:
 visualizer:
  image: dockersamples/visualizer:stable
  ports:
   - 8000:8080
  volumes:
   - "/var/run/docker.sock:/var/run/docker.sock"
  deploy:
   mode: replicated
   replicas: 1
   labels: [APP=MONITOR]
   placement:
    constraints: [node.role == manager]
 registry:
    image: registry:2
    ports:
      - 5000:5000
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
    volumes:
      - "/home/centos/docker/persistence/registry:/var/lib/registry"
networks:
 gestbook-net:

