version: "3"

services:
  registry:
    image: registry:latest
    ports:
      - 5000:5000
    networks:
      - registry
    volumes:
      - mahregistry:/var/lib/registry
    deploy:
      labels: [APP=REGISTRY]
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  registry:

volumes:
  mahregistry:
  dataportainer:
