version: '3'

services:
 prometheus:
    image: prom/prometheus
    ports:
      - 8002:9090
    volumes:
      - "/home/centos/docker/persistence/prometheus/:/etc/prometheus/"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=PROMETHEUS]
      placement:
        constraints: [node.role == manager]
 grafana:
  image: grafana/grafana
  ports:
    - 8003:3000
  deploy:
   mode: replicated
   replicas: 1
   labels: [APP=GRAFANA]
   placement:
    constraints: [node.role == manager]
 infonode:
   image: prom/node-exporter
   ports:
      - 9100:9100
   deploy:
      mode: global
