apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplelogger-nfsstorage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
      - name: logger
        image: moconinja/simplelogger
        volumeMounts:
        - name: nfs-pvc
          mountPath: /logs
      volumes:
      - name: nfs-pvc
        persistentVolumeClaim:
          claimName: nfs-pvc
