scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.2.14:9100', '192.168.2.15:9100', '192.168.2.13:9100', '192.168.2.18:9100']

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "MONITOR_alertmanager:9093"

rule_files:
  - 'alert.rules'
